[project]
name = ""
version = "0.0.1"
requires-python = "~=3.12"
dependencies = [
    "matplotlib",
    "numpy",
    "requests",
    "pydantic",
    "xarray",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
